[package]
name = "ftc_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.5"
iced_native = "0.6.1"
iced_lazy = "0.2.0"
ftc_http = "2"
serde = "1.0.150"
serde_json = "1.0.89"