name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Rust Cache
      # You may pin to the exact commit or the version.
      # uses: Swatinem/rust-cache@6fd3edff6979b79f87531400ad694fb7f2c84b1f
      uses: Swatinem/rust-cache@v2.2.1
      with:
        cache-on-failure: false

    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
